#!/bin/sh

# post-checkout hook for Sketch files Git tracking

# Set UTF-8 encoding
export LANG=UTF-8
# Needed to work in SourceTree
export PATH=/usr/local/bin:$PATH

# Git repository absolute path
git_root=`git rev-parse --show-toplevel`
# Unzipped Sketch files path
unzipped_directory_name="_unzipped"
unzipped_root="$git_root/$unzipped_directory_name"
# Local backups directory path
backup_root="$git_root/_backup"

for unzipped_directory in $(find "$unzipped_directory_name" -type d | grep ".sketch$")
do

  # Sketch file path
  sketch=`echo "$git_root/$unzipped_directory" | sed "s/$unzipped_directory_name\///"`
  # Sketch file directory path
  sketch_directory=`dirname "$sketch"`

  echo "Processing '`basename $sketch`'."

  if mkdir -p "$sketch_directory"
  then

    # Backup existing Sketch file - in case re-creating the sketch file fails
    backup_path=`echo "$backup_root/$(date +"%Y-%m-%d-%H-%M-%S")/$unzipped_directory" | sed "s/$unzipped_directory_name\///"`
    mkdir -p "`dirname $backup_path`"
    mv "$sketch" "$backup_path"

    # Zip the directory to recreate the Sketch file
    cd "$unzipped_directory"

    # Set access and modified times of all files going into the archive. This
    # keeps them consistent, so the hashes of archives with identical file
    # contents will be identical. Otherwise we get into nasty situations where
    # the sketch files seem to be changing after every merge and checkout, but
    # they aren't (because they were re-created with identical files with
    # different timestamps).
    touch -a -m -t 197001010000.00 {*,**/*}

    # rqX = recursive, quiet, exclude extra file attributes
    if zip -rqX "$sketch" *
    then
      echo "  '`basename $sketch`' Sketch file generated."
    else
      echo "  Couldn't generate '`basename $sketch`' Sketch file."
      exit 1
    fi
    cd "$git_root"
  else
    echo "  Couldn't create '$sketch_directory' directory."
    exit 1
  fi

  # the creation of all the sketch files was successful, so remove the backups
  rm -r ${backup_root}

done
