#!/bin/sh

echo "\033[0;35m[> installing 3rd-party software...\n\033[0m"

# install 3rd-party software
brew install python3 node
# install any npm modules
npm install

# install hooks
./install-hooks
